//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountInfor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountInfor()
        {
            this.StoreInfors = new HashSet<StoreInfor>();
        }
    
        public int ID { get; set; }
        public string Fullname { get; set; }
        public string Shortname { get; set; }
        public int ChannelID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ChannelInfor ChannelInfor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreInfor> StoreInfors { get; set; }
    }
}
