//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerInfor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnswerInfor()
        {
            this.AnswerRecords = new HashSet<AnswerRecord>();
        }
    
        public int ID { get; set; }
        public long CheckinInforID { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    
        public virtual CheckinInfor CheckinInfor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerRecord> AnswerRecords { get; set; }
    }
}
