//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerRecord
    {
        public int ID { get; set; }
        public int AnswerID { get; set; }
        public int QuesionID { get; set; }
        public string AnswerOption { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    
        public virtual AnswerInfor AnswerInfor { get; set; }
        public virtual QuestionInfor QuestionInfor { get; set; }
    }
}
