//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentCourseRecord
    {
        public long ID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> ContentID { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    
        public virtual ContentInfor ContentInfor { get; set; }
        public virtual CourseInfor CourseInfor { get; set; }
    }
}
