//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentModelRecord
    {
        public int ID { get; set; }
        public Nullable<int> ContentID { get; set; }
        public Nullable<int> ModelID { get; set; }
    
        public virtual ContentInfor ContentInfor { get; set; }
        public virtual ModelInfor ModelInfor { get; set; }
    }
}
