//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelInfor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModelInfor()
        {
            this.ContentModelRecords = new HashSet<ContentModelRecord>();
        }
    
        public int ID { get; set; }
        public int CatID { get; set; }
        public string Modelcode { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual CatInfor CatInfor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentModelRecord> ContentModelRecords { get; set; }
    }
}
