//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestionRecord
    {
        public int ID { get; set; }
        public int TestID { get; set; }
        public int QuestionID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> QuestionOrder { get; set; }
        public virtual QuestionInfor QuestionInfor { get; set; }
        public virtual TestInfor TestInfor { get; set; }
    }
}
