//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerInfor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainerInfor()
        {
            this.RoomInfors = new HashSet<RoomInfor>();
            this.TrainerRoomRecords = new HashSet<TrainerRoomRecord>();
        }
    
        public int ID { get; set; }
        public int ProvinceID { get; set; }
        public int PositionID { get; set; }
        public string Fullname { get; set; }
        public string Tel { get; set; }
        public bool Status { get; set; }
    
        public virtual PositionInfor PositionInfor { get; set; }
        public virtual ProvinceInfor ProvinceInfor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomInfor> RoomInfors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerRoomRecord> TrainerRoomRecords { get; set; }
    }
}
