//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerRoomRecord
    {
        public int ID { get; set; }
        public int RoomID { get; set; }
        public int TrainerID { get; set; }
    
        public virtual RoomInfor RoomInfor { get; set; }
        public virtual TrainerInfor TrainerInfor { get; set; }
    }
}
