//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfor()
        {
            this.LoginInfors = new HashSet<LoginInfor>();
            this.TrainerRoomRecords = new HashSet<TrainerRoomRecord>();
            this.CheckinInfors = new HashSet<CheckinInfor>();
        }
    
        public int ID { get; set; }
        public int PositionID { get; set; }
        public string Tel { get; set; }
        public string Password { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int EmployeeID { get; set; }
        public int PermissionID { get; set; }
    
        public virtual EmployeeInfor EmployeeInfor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginInfor> LoginInfors { get; set; }
        public virtual PositionInfor PositionInfor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerRoomRecord> TrainerRoomRecords { get; set; }
        public virtual PermissionInfor PermissionInfor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckinInfor> CheckinInfors { get; set; }
    }
}
