//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckInApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfor()
        {
            this.CheckinInfors = new HashSet<CheckinInfor>();
            this.LoginInfors = new HashSet<LoginInfor>();
            this.UserPermissionRecords = new HashSet<UserPermissionRecord>();
        }
    
        public int ID { get; set; }
        public int StoreID { get; set; }
        public int PositionID { get; set; }
        public string Fullname { get; set; }
        public string Tel { get; set; }
        public string Password { get; set; }
        public bool Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string MNV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckinInfor> CheckinInfors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginInfor> LoginInfors { get; set; }
        public virtual PositionInfor PositionInfor { get; set; }
        public virtual StoreInfor StoreInfor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPermissionRecord> UserPermissionRecords { get; set; }
    }
}
